### ISSUE TITLE
Needs license info...

### ISSUE THREAD

**Issue by WestfW** [anydream/TurboSPI#1]
This is lovely code; nice and simple, and provides a significant performance boost on Due.
But it should have licensing information attached describing how other may use it.
(Please be MIT or BSD or some other "permissive"  license.  Even LGPL wouldn't be too bad.  But if it's really extracted from the SDFAT library I've seen floating around, it probably inherits a GPL license.  (and should probably contain more attribution.)
https://en.wikipedia.org/wiki/Comparison_of_free_and_open-source_software_licenses

**Comment by anydream** [comment]
License file added, Thank you for reminding me.
